name: sorot_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # FlutterFire (versi yang saling cocok)
  firebase_core: ^4.1.0
  cloud_firestore: ^6.0.1
  firebase_auth: ^6.0.2     # <-- upgrade sesuai saran solver
  firebase_storage: ^13.0.1
  # firebase_app_check: (biarkan nonaktif dulu sampai semua lancar)

  # Lainnya
  http: ^1.2.2
  image_picker: ^1.1.2
  http_parser: ^4.0.2
  mime: ^1.0.5



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/