// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClLa_Ps8PoCy9YU4IVvriOSlhfjJeKokM',
    appId: '1:647800295624:web:ab010a410cfe35416f95fd',
    messagingSenderId: '647800295624',
    projectId: 'sorot-app-13097',
    authDomain: 'sorot-app-13097.firebaseapp.com',
    storageBucket: 'sorot-app-13097.firebasestorage.app',
    measurementId: 'G-X0LXLJXBT2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFrfkA9tKZOojbIgFbzAVGt_MWLmn71-w',
    appId: '1:647800295624:android:aecf224967f44bcd6f95fd',
    messagingSenderId: '647800295624',
    projectId: 'sorot-app-13097',
    storageBucket: 'sorot-app-13097.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzTmDtChoIUs9YdiuuPreCgpxeYaTWWwo',
    appId: '1:647800295624:ios:2c3ad495cf20fbdd6f95fd',
    messagingSenderId: '647800295624',
    projectId: 'sorot-app-13097',
    storageBucket: 'sorot-app-13097.firebasestorage.app',
    iosBundleId: 'com.example.sorotApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzTmDtChoIUs9YdiuuPreCgpxeYaTWWwo',
    appId: '1:647800295624:ios:2c3ad495cf20fbdd6f95fd',
    messagingSenderId: '647800295624',
    projectId: 'sorot-app-13097',
    storageBucket: 'sorot-app-13097.firebasestorage.app',
    iosBundleId: 'com.example.sorotApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClLa_Ps8PoCy9YU4IVvriOSlhfjJeKokM',
    appId: '1:647800295624:web:cd2686bea15a5bef6f95fd',
    messagingSenderId: '647800295624',
    projectId: 'sorot-app-13097',
    authDomain: 'sorot-app-13097.firebaseapp.com',
    storageBucket: 'sorot-app-13097.firebasestorage.app',
    measurementId: 'G-HFVQEB89DW',
  );
}
